.TH 42SH 1  "14 November 2019" 42SH

.SH NAME
.P
42sh \- An EPITA's Project
.SH DESCRIPTION
.P
\fB42sh\fR is an \fBshell\fR-compatible command language interpreter that
executes commands read from the standard input or from a file.

.P
\fB42sh\fR is implemented using \fIC\fR language and tested using \fI Python\fR and \fI Criterion\fR. It tries to repect the "EPITA C99 Coding Style" and the standard \fISCL\fR (Shell Command Langage).

.SH OPTION

.P

42sh posseses some options when it is not in the interactive mode, those options are:

.B \-\-ast\-print
Activate the ast printer.

.B \-\-ast\-print
Activate the ast printer.

.B \-\-ast\-print
Activate the ast printer.

.B \-\-ast\-print
Activate the ast printer.

.SH INVOCATION
.P
.PP

To use our shell in interactive mode you just have to use the binary without arguments otherwise it will take input such has bash commands or file.

.SH MADE BY

Julie Hazan, Paul Adam, Mathieu Tamaro, Alexandre Bourquelot
